#This file is used to define the properties of the application, such as the name of the application, the port number, the database connection, etc. We can also define our own properties and use them in our application.

spring.application.name=moshCode
server.port=9090
app.page-size=10