package com.moshCourse.moshCode;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class MoshCodeApplication {

	public static void main(String[] args) {
	//	SpringApplication.run(MoshCodeApplication.class, args);

	var orderService = new OrderService(new PayPalPaymentService());
	orderService.placeOrder();
	}

}
//open closed principle: open for extension, closed for modification, we can add new payment services without modifying the existing code, and we can use the existing code without worrying about breaking it.
//add new classes without modifying the existing code, we can add new payment services without modifying the existing code, and we can use the existing code without worrying about breaking it.
//@Service Business logic
// @Repository Data access logic
// @Controller Web layer logic
//RestController: @RestController is a specialized version of @Controller that combines @Controller and @ResponseBody, which means that it is used to create RESTful web services. It is typically used to handle HTTP requests and return JSON or XML responses.
//restart the video a 1h