package com.moshCourse.moshCode;

public interface PaymentService {
    void processPayment(double amount); 

}
//interface is a contract that defines a method without implementation. Classes that implement this interface must provide an implementation for the processPayment method.
//interfaces are used to achieve abstraction and multiple inheritance in Java. They allow us to define a set of methods that a class must implement, without specifying how those methods should be implemented.
//In this case, the PaymentService interface defines a contract for processing payments. Any class that implements this interface must provide an implementation for the processPayment method, which takes a double amount as a parameter. This allows us to create different payment service implementations (e.g., StripePaymentService, PayPalPaymentService) that can be used interchangeably as long as they adhere to the PaymentService contract.
//By using an interface, we can decouple the OrderService from the specific implementation of the payment processing. This promotes flexibility and maintainability in our code, as we can easily switch out different payment service implementations without modifying the OrderService class.
//In summary, the PaymentService interface defines a contract for processing payments, and any class that implements this interface must provide an implementation for the processPayment method. This allows us to create different payment service implementations that can be used interchangeably in our application.
//In the OrderService class, we can create an instance of a specific payment service (e.g., StripePaymentService) and call the processPayment method to process the payment for an order. This allows us to keep the OrderService class focused on its primary responsibility of managing orders, while delegating the payment processing to a separate class that implements the PaymentService interface.
//Interfaces are a template that can be applied to a class. like inheriance but it specifies what a class should do, not how it should do it. It defines a contract that a class must adhere to, without providing any implementation details. This allows for greater flexibility and modularity in our code, as we can create different implementations of the same interface without affecting the rest of the codebase. In this case, the PaymentService interface defines a contract for processing payments, and any class that implements this interface must provide an implementation for the processPayment method. This allows us to create different payment service implementations (e.g., StripePaymentService, PayPalPaymentService) that can be used interchangeably in our application.
//classes that implement the PaymentService interface must provide an implementation for the processPayment method, which takes a double amount as a parameter. This allows us to create different payment service implementations (e.g., StripePaymentService, PayPalPaymentService) that can be used interchangeably as long as they adhere to the PaymentService contract.
//Classes can also implement multiple interfaces, allowing for greater flexibility and modularity in our code. For example, a class could implement both the PaymentService interface and another interface that defines additional functionality related to order processing. This allows us to create classes that can handle multiple responsibilities while still adhering to the contracts defined by the interfaces they implement.
